#!/usr/bin/env bash
# GPU-free evidence checks for Stage 6 contracts/tooling.
set -euo pipefail

cd "$(dirname "$0")/.."
python3 scripts/test_stage6_p2o_evidence_tools.py
python3 scripts/test_stage6_p3_contract_static.py
python3 scripts/test_stage6_p3a_evidence_tools.py
python3 scripts/test_stage6_gpu_gate_suite.py
python3 scripts/test_stage6_p3b_contract_static.py
python3 scripts/test_stage6_p3b_evidence_tools.py
python3 scripts/test_stage6_p3c_evidence_tools.py
python3 scripts/test_stage6_p3d_evidence_tools.py
python3 scripts/test_stage6_p3e_evidence_tools.py
python3 scripts/test_stage6_p4_native_abi_static.py
python3 scripts/test_stage6_p4_evidence_tools.py
python3 scripts/test_stage6_p4_zero_shadow_firewall.py
python3 scripts/test_stage6_p4_runtime_bridge_tools.py
python3 scripts/test_stage6_p4b_single_kernel_static.py
python3 scripts/test_stage6_p4b_single_kernel_evidence_tools.py
python3 scripts/test_stage6_p4b_runtime_bridge_tools.py
python3 scripts/test_stage6_p4b_single_cta_numeric_tools.py
python3 scripts/test_stage6_p4b_single_cta_microbench_tools.py
python3 scripts/test_stage6_p4c_active_reuse_decision_static.py
python3 scripts/test_stage6_p4c_runtime_bridge_tools.py
python3 scripts/test_stage6_p4c_active_reuse_microbench_tools.py
python3 scripts/test_stage6_p4c_component_profile_tools.py
python3 scripts/test_stage6_p4c_gateup_shape_sweep_tools.py
python3 scripts/test_stage6_p4c_gateup_shape_candidate_tools.py
python3 scripts/test_stage6_p4c_tile2_server_smoke_tools.py
python3 scripts/test_stage6_decode_gpu_idle_probe_tools.py
python3 scripts/test_stage6_r6000_fp4_mma_census_tools.py
scripts/test_stage6_r6000_autodl_bootstrap_static.sh
python3 scripts/test_stage6_r6000_grouped_moe_poc_contract_static.py
python3 scripts/test_stage6_evidence_ledger.py
